version: 2.1

jobs:
  main:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Run build
          command: yarn nx build cart

workflows:
  version: 2

  ci:
    jobs:
      - main:
          name: Nx Cloud Main
